### PR TITLE
[fix] modify kernel address

### PR DESCRIPTION
**Pull request by wenhu1024**
the vectorAdd kernel address is not right, so i fix it.

`riscv64-unknown-elf-objdump -d vecadd.riscv | grep vectorAdd
` 

`800000b8 <vectorAdd>:`

### CODE REVIEW

**Comment by wenhu1024** [comment]
vecadd.cl is below

`__kernel void vectorAdd(__global float* A, __global float* B) {
  unsigned tid = get_global_id(0);
  A[tid] += B[tid];
}`

<br>

 vecadd.riscv 
`./install/bin/clang -cl-std=CL2.0 -target riscv32 -mcpu=ventus-gpgpu vecadd.cl  ./install/lib/crt0.o -L./install/lib -lworkitem -I./libclc/generic/include -nodefaultlibs ./libclc/riscv32/lib/workitem/get_global_id.cl -O1 -cl-std=CL2.0 -Wl,-T,utils/ldscripts/ventus/elf32lriscv.ld -o vecadd.riscv`

**Comment by reoLantern** [comment]
I tested the default test case file from the repository and found that the original address (0x80000098) works correctly and provides the expected functionality. The test case file used is `gpgpu-testcase/vsw_testcase/vecadd.riscv`, and the address can also be verified through `gpgpu-testcase/vsw_testcase/vecadd.dump`. Therefore, I believe no changes are necessary at this point.

That said, this bare-metal mode test has not been maintained for quite a while. It might be a good idea to refactor it and define a more robust interface. 

Thank you very much for your contribution!

**Comment by wenhu1024** [comment]
Got it! It's because the vecadd.cl I used earlier didn't have a printf statement, which makes it different from the vecadd.cl in gpgpu-testcase/vsw_testcase.

**Comment by wenhu1024** [comment]
The version of the llvm-project repository has been updated. The new version of the compiler compiles the kernel to a RISC-V file, and the generated kernel address is not 0x80000098, but 0x800000b8.

Although the kernel address in gpgpu-testcase/vsw_testcase/vecadd.riscv is 0x80000098. This means that this test.cpp can only test the gpgpu-testcase/vsw_testcase/vecadd.riscv file. 

We can modify the CMake file to set a macro and manually change the kernel address.

**Comment by wenhu1024** [comment]
## Background
The llvm-project update changed the compiler's kernel function address:
- New version: `0x800000b8`
- Old `gpgpu-testcase/vsw_testcase/vecadd.riscv`: `0x80000098`

## Changes
Modified CMakeLists.txt to add a configurable `KERNEL_ADDRESS` macro:
- Default: `0x800000b8` (new LLVM)
- For old kernels: `cmake -DKERNEL_ADDRESS=0x80000098`

**Review by reoLantern — DISMISSED** [review]
The changes make sense and address the compatibility issue. I'll merge this.

**Comment by wenhu1024** [comment]
Thank you！

**Review by reoLantern — APPROVED** [review]
approve

**Pull request merged**
