### PR TITLE
[fix] fix memory access fault by adding interface of free one memory block

### LINKED ISSUE #18: 没有释放某一块内存的接口，

### PR DESCRIPTION
**Pull request by yangzexia**
(cherry picked from commit 9d27a64b5aefef646b6b79fce39e2ae803289175)
#18

### CODE REVIEW

**Comment by yangzexia** [comment]
LGTM

**Review by Jules-Kong — APPROVED** [review]
LGTM

**Comment by Jules-Kong** [comment]
Improve the information description.

**Comment by Jules-Kong** [comment]
Related pr ：
* driver：https://github.com/THU-DSP-LAB/ventus-driver/pull/3 
* pocl：  https://github.com/THU-DSP-LAB/pocl/pull/50
* spike： https://github.com/THU-DSP-LAB/ventus-gpgpu-isa-simulator/pull/19

**Comment by Jules-Kong** [comment]
Parameters taskID and kernelD are reserved for multi-tasking scenarios.

**Pull request merged**
